// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Terminal is one terminal emulator available on the host.
 */
export interface Terminal {
    "id": string;
    "name": string;
    "binary": string;
}
