// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillItem is one discovered skill or command, keyed by its store slug, kind
 * and name; nothing references an item by database id.
 */
export interface SkillItem {
    "store": string;
    "kind": string;
    "name": string;
    "description": string;
    "plugin": string;
    "rel_path": string;
}
