// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheMount is a shared host directory mounted into sandboxes at a
 * toolchain-specific target path (Go module cache, npm cache, …).
 */
export interface CacheMount {
    "id": number;
    "name": string;
    "description": string;
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
    "auto_attach": boolean;
    "enabled": boolean;
    "created_at": string;
    "updated_at": string;
}

/**
 * KitStore is a git checkout of a kit repository.
 */
export interface KitStore {
    "id": number;
    "name": string;
    "description": string;
    "url": string;
    "ref": string;
    "auth": string;
    "path": string;
    "synced_at": string;
    "error": string;
    "created_at": string;
    "updated_at": string;
}

/**
 * Profile is a named, reusable set of allow/deny URL patterns.
 */
export interface Profile {
    "id": number;
    "name": string;
    "description": string;
    "is_default": boolean;
    "is_global": boolean;
    "created_at": string;
    "updated_at": string;
}

/**
 * ProfileMount is a bind mount a profile applies by default to every sandbox
 * it is assigned to. It is applied at runtime (like caches) and re-applied by
 * the reconcile pass whenever the sandbox is running.
 */
export interface ProfileMount {
    "id": number;
    "profile_id": number;
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
    "created_at": string;
}

/**
 * Rule is one allow/deny pattern belonging to a profile.
 */
export interface Rule {
    "id": number;
    "profile_id": number;
    "decision": string;
    "pattern": string;
    "created_at": string;
}

/**
 * SkillItem is one skill or command discovered in a store checkout.
 */
export interface SkillItem {
    "id": number;
    "store_id": number;
    "store_name": string;
    "kind": string;
    "name": string;
    "description": string;
    "plugin": string;
    "rel_path": string;
}

/**
 * SkillStore is a git checkout of an Anthropic-format plugin repository.
 */
export interface SkillStore {
    "id": number;
    "name": string;
    "description": string;
    "url": string;
    "ref": string;
    "auth": string;
    "path": string;
    "synced_at": string;
    "error": string;
    "created_at": string;
    "updated_at": string;
}
