// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Desktop is the Wails binding surface. Every exported method becomes a
 * typed frontend binding; nothing is reachable from outside the process.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fleet$0 from "../fleet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sbx$0 from "../sbx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "../search/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "../terminal/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddMount declares a bind mount in the sandbox config and attaches it.
 */
export function AddMount(name: string, req: $models.MountRequest): $CancellablePromise<void> {
    return $Call.ByID(3191530632, name, req);
}

/**
 * AddProfileCache adds a shared cache to a profile.
 */
export function AddProfileCache(profileSlug: string, cacheSlug: string): $CancellablePromise<void> {
    return $Call.ByID(1979491754, profileSlug, cacheSlug);
}

/**
 * AddProfileMount declares a mount on a profile.
 */
export function AddProfileMount(profileSlug: string, req: $models.ProfileMountRequest): $CancellablePromise<fleet$0.MountRef> {
    return $Call.ByID(3944258429, profileSlug, req);
}

/**
 * AddProfileSkillItem selects a catalog item on a profile.
 */
export function AddProfileSkillItem(profileSlug: string, ref: $models.SkillRefRequest): $CancellablePromise<void> {
    return $Call.ByID(159872622, profileSlug, ref);
}

/**
 * AddRule appends an allow/deny pattern to a profile.
 */
export function AddRule(slug: string, req: $models.RuleRequest): $CancellablePromise<void> {
    return $Call.ByID(1446732289, slug, req);
}

/**
 * ApplyProfileCache clears the opt-out and attaches the cache.
 */
export function ApplyProfileCache(name: string, cacheSlug: string): $CancellablePromise<void> {
    return $Call.ByID(2344918061, name, cacheSlug);
}

/**
 * ApplyProfileMount clears the opt-out and attaches the mount.
 */
export function ApplyProfileMount(name: string, hostPath: string, targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(3368313858, name, hostPath, targetPath);
}

/**
 * ApplySandbox converges a running sandbox onto its files as a job.
 */
export function ApplySandbox(name: string, jobID: string): $CancellablePromise<string> {
    return $Call.ByID(3427142839, name, jobID);
}

/**
 * AssignProfile applies a profile to a sandbox.
 */
export function AssignProfile(name: string, profileSlug: string): $CancellablePromise<void> {
    return $Call.ByID(1221982478, name, profileSlug);
}

/**
 * AttachCache declares a direct cache attachment on a sandbox.
 */
export function AttachCache(name: string, cacheSlug: string): $CancellablePromise<void> {
    return $Call.ByID(2232078297, name, cacheSlug);
}

/**
 * AttachKit attaches a mixin kit to an existing sandbox: `sbx kit add`
 * recreates the container while preserving kit-owned volumes and --clone
 * workspaces, then the sidecar is re-applied and its report returned.
 */
export function AttachKit(name: string, ref: string): $CancellablePromise<app$0.KitAddResult> {
    return $Call.ByID(4277206571, name, ref);
}

/**
 * AttachSkillItem selects a catalog item directly on a sandbox.
 */
export function AttachSkillItem(name: string, ref: $models.SkillRefRequest): $CancellablePromise<void> {
    return $Call.ByID(29893609, name, ref);
}

/**
 * CancelJob stops a running job.
 */
export function CancelJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(1409963593, id);
}

/**
 * CheckUpdates queries the latest stable release. A cached result is returned
 * when the last check is fresh unless force is set.
 */
export function CheckUpdates(force: boolean): $CancellablePromise<$models.VersionInfo> {
    return $Call.ByID(3456224186, force);
}

/**
 * CompleteSandboxConfig records the create parameters an imported sandbox was
 * missing and clears its incomplete marker.
 */
export function CompleteSandboxConfig(name: string, req: $models.CompleteSandboxRequest): $CancellablePromise<void> {
    return $Call.ByID(1617825496, name, req);
}

/**
 * ConfigStaleness reports the loaded configuration files that changed on disk
 * since the last load; the UI polls it on window focus and on a short interval.
 */
export function ConfigStaleness(): $CancellablePromise<fleet$0.Staleness> {
    return $Call.ByID(3032756432);
}

/**
 * CreateCache writes a shared cache definition.
 */
export function CreateCache(input: $models.CacheInput): $CancellablePromise<fleet$0.Cache> {
    return $Call.ByID(3252116970, input);
}

/**
 * CreateKitStore registers, checks out and discovers a kit repository.
 */
export function CreateKitStore(req: $models.KitStoreRequest): $CancellablePromise<app$0.KitStoreView> {
    return $Call.ByID(4023927925, req);
}

/**
 * CreateProfile writes a new profile and returns its view.
 */
export function CreateProfile(req: $models.ProfileRequest): $CancellablePromise<app$0.ProfileView> {
    return $Call.ByID(1812190421, req);
}

/**
 * CreateSandbox validates the request and starts `sbx create` as a job,
 * writing the new sandbox's config directory and converging it.
 */
export function CreateSandbox(req: $models.CreateSandboxRequest): $CancellablePromise<string> {
    return $Call.ByID(1064106591, req);
}

/**
 * CreateSkillStore registers, checks out and discovers a skill store.
 */
export function CreateSkillStore(req: $models.SkillStoreRequest): $CancellablePromise<app$0.SkillStoreView> {
    return $Call.ByID(284057750, req);
}

/**
 * DeleteCache removes a shared cache definition and detaches it everywhere.
 */
export function DeleteCache(slug: string): $CancellablePromise<void> {
    return $Call.ByID(3374406371, slug);
}

/**
 * DeleteKitStore forgets a kit repository, its checkout and its catalog.
 */
export function DeleteKitStore(slug: string): $CancellablePromise<void> {
    return $Call.ByID(3030112906, slug);
}

/**
 * DeleteProfile removes a profile file and everything it applied.
 */
export function DeleteProfile(slug: string): $CancellablePromise<void> {
    return $Call.ByID(3438322432, slug);
}

/**
 * DeleteSandbox removes a sandbox, optionally purging its config directory.
 */
export function DeleteSandbox(name: string, force: boolean, purgeConfig: boolean): $CancellablePromise<void> {
    return $Call.ByID(3704837250, name, force, purgeConfig);
}

/**
 * DeleteSkillStore forgets a skill store, its checkout and its catalog.
 */
export function DeleteSkillStore(slug: string): $CancellablePromise<void> {
    return $Call.ByID(544048789, slug);
}

/**
 * DetachCache revokes a direct cache attachment from a sandbox.
 */
export function DetachCache(name: string, cacheSlug: string): $CancellablePromise<void> {
    return $Call.ByID(819031591, name, cacheSlug);
}

/**
 * DetachProfileCache opts a sandbox out of one profile cache.
 */
export function DetachProfileCache(name: string, cacheSlug: string): $CancellablePromise<void> {
    return $Call.ByID(539355638, name, cacheSlug);
}

/**
 * DetachProfileMount opts a sandbox out of one profile mount.
 */
export function DetachProfileMount(name: string, hostPath: string, targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(2508477465, name, hostPath, targetPath);
}

/**
 * DetachSkillItem drops a direct selection from a sandbox.
 */
export function DetachSkillItem(name: string, ref: $models.SkillRefRequest): $CancellablePromise<void> {
    return $Call.ByID(2772222383, name, ref);
}

/**
 * Exec starts a one-shot command in the sandbox, returning the job id whose
 * output streams over hub events.
 */
export function Exec(name: string, req: $models.ExecRequest): $CancellablePromise<string> {
    return $Call.ByID(2003739213, name, req);
}

/**
 * FleetDir returns the configuration directory that holds every file.
 */
export function FleetDir(): $CancellablePromise<string> {
    return $Call.ByID(2207462495);
}

/**
 * GetConfig returns the global sandwarden configuration (terminal launcher
 * and desktop notifications preferences).
 */
export function GetConfig(): $CancellablePromise<fleet$0.AppConfig> {
    return $Call.ByID(2427447342);
}

/**
 * Health reports the daemon socket and CLI in use.
 * Health reports the sandboxd daemon state along with the socket and CLI in
 * use.
 */
export function Health(): $CancellablePromise<$models.Health> {
    return $Call.ByID(3798447474);
}

/**
 * ImportSandboxes adopts the named daemon sandboxes, or every daemon sandbox
 * when the request names none, into the config directory. Adopted configs
 * missing create parameters are marked incomplete.
 */
export function ImportSandboxes(req: $models.ImportSandboxesRequest): $CancellablePromise<app$0.ImportReport> {
    return $Call.ByID(2418394828, req);
}

/**
 * ImportSecrets starts a bulk import as a job, returning the job id whose
 * output streams over hub events.
 */
export function ImportSecrets(req: $models.ImportSecretsRequest): $CancellablePromise<string> {
    return $Call.ByID(3098023610, req);
}

/**
 * Job returns the buffered view of a streamed job.
 */
export function Job(id: string): $CancellablePromise<app$0.JobView> {
    return $Call.ByID(700660519, id);
}

/**
 * KitValidate runs `sbx kit validate` over one catalog kit.
 */
export function KitValidate(storeSlug: string, name: string): $CancellablePromise<app$0.KitValidation> {
    return $Call.ByID(1692091598, storeSlug, name);
}

/**
 * ListCaches returns every shared cache definition.
 */
export function ListCaches(): $CancellablePromise<fleet$0.Cache[] | null> {
    return $Call.ByID(3090063311);
}

/**
 * ListKitItems returns the discovered kits of one store, or all of them when
 * storeSlug is empty.
 */
export function ListKitItems(storeSlug: string): $CancellablePromise<app$0.KitItemView[] | null> {
    return $Call.ByID(3866323812, storeSlug);
}

/**
 * ListKitStores returns every registered kit repository.
 */
export function ListKitStores(): $CancellablePromise<app$0.KitStoreView[] | null> {
    return $Call.ByID(4045162982);
}

/**
 * ListProfiles returns every profile with its rules and sandbox assignments.
 */
export function ListProfiles(): $CancellablePromise<app$0.ProfileView[] | null> {
    return $Call.ByID(725903486);
}

/**
 * ListSandboxes returns live sandbox summaries with their config profiles.
 */
export function ListSandboxes(): $CancellablePromise<app$0.SandboxSummary[] | null> {
    return $Call.ByID(1965913211);
}

/**
 * ListSecrets returns stored and custom secrets for one scope.
 */
export function ListSecrets(scope: string): $CancellablePromise<sbx$0.SecretList> {
    return $Call.ByID(3135961433, scope);
}

/**
 * ListSkillItems returns the discovered items of one store, or all of them
 * when storeSlug is empty.
 */
export function ListSkillItems(storeSlug: string): $CancellablePromise<store$0.SkillItem[] | null> {
    return $Call.ByID(3147280427, storeSlug);
}

/**
 * ListSkillStores returns every registered skill store.
 */
export function ListSkillStores(): $CancellablePromise<app$0.SkillStoreView[] | null> {
    return $Call.ByID(969324587);
}

/**
 * ListTemplates returns the template images of the local sandbox runtime.
 */
export function ListTemplates(): $CancellablePromise<sbx$0.Template[] | null> {
    return $Call.ByID(3828726815);
}

/**
 * ListTerminals reports the terminal emulators found on this host, most
 * common first. It feeds the Open button dropdown and the Settings panel.
 */
export function ListTerminals(): $CancellablePromise<terminal$0.Terminal[] | null> {
    return $Call.ByID(549832973);
}

/**
 * OpenInTerminal opens dir in the chosen terminal and runs command there, so
 * sandbox connect commands start in the workspace directory.
 */
export function OpenInTerminal(terminalID: string, dir: string, command: string): $CancellablePromise<void> {
    return $Call.ByID(1192281911, terminalID, dir, command);
}

/**
 * PickFolder opens the host's native folder chooser rooted at start.
 */
export function PickFolder(start: string): $CancellablePromise<string> {
    return $Call.ByID(2730484725, start);
}

/**
 * PolicyAction applies a global policy mutation.
 */
export function PolicyAction(req: $models.PolicyActionRequest): $CancellablePromise<sbx$0.PolicyActionResult[] | null> {
    return $Call.ByID(3170893108, req);
}

/**
 * PolicyRules returns network policy rules, optionally filtered by sandbox.
 */
export function PolicyRules(sandbox: string): $CancellablePromise<sbx$0.PolicyRule[] | null> {
    return $Call.ByID(3653743041, sandbox);
}

/**
 * ProfileConfigDir returns the config directory of a profile.
 */
export function ProfileConfigDir(slug: string): $CancellablePromise<string> {
    return $Call.ByID(3352570098, slug);
}

/**
 * ReadProfileConfig returns the raw spec.yaml and sandwarden.yaml of a
 * profile for the read-only viewer.
 */
export function ReadProfileConfig(slug: string): $CancellablePromise<app$0.ConfigFile[] | null> {
    return $Call.ByID(4168180847, slug);
}

/**
 * ReadSandboxConfig returns the raw spec.yaml and sandwarden.yaml of a
 * sandbox for the read-only viewer. A broken file is reported in its own
 * ConfigFile entry, so the viewer still shows the raw text and the parse error.
 */
export function ReadSandboxConfig(name: string): $CancellablePromise<app$0.ConfigFile[] | null> {
    return $Call.ByID(177617797, name);
}

/**
 * ReapplyCaches re-attaches every desired cache; failures are reported per
 * cache instead of aborting the batch.
 */
export function ReapplyCaches(name: string): $CancellablePromise<$models.ReapplyResult> {
    return $Call.ByID(324324692, name);
}

/**
 * ReconcileSkills converges the sandbox's .agents mounts.
 */
export function ReconcileSkills(name: string): $CancellablePromise<app$0.SkillReconcileResult> {
    return $Call.ByID(361613106, name);
}

/**
 * RecreateSandbox deletes and recreates a sandbox from its files as a job.
 */
export function RecreateSandbox(name: string, jobID: string): $CancellablePromise<string> {
    return $Call.ByID(292371004, name, jobID);
}

/**
 * RefreshKitStore re-runs the checkout and discovery.
 */
export function RefreshKitStore(slug: string): $CancellablePromise<app$0.KitStoreView> {
    return $Call.ByID(3312291690, slug);
}

/**
 * RefreshSkillStore re-runs the checkout and discovery.
 */
export function RefreshSkillStore(slug: string): $CancellablePromise<app$0.SkillStoreView> {
    return $Call.ByID(1436103669, slug);
}

/**
 * ReloadFleet re-reads every configuration file from disk and returns the
 * per-file errors, if any.
 */
export function ReloadFleet(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3679538611);
}

/**
 * RemoveCustomSecret deletes a custom secret by placeholder.
 */
export function RemoveCustomSecret(scope: string, placeholder: string): $CancellablePromise<void> {
    return $Call.ByID(2743726951, scope, placeholder);
}

/**
 * RemoveMount removes a declared bind mount and detaches it.
 */
export function RemoveMount(name: string, path: string, target: string): $CancellablePromise<void> {
    return $Call.ByID(4168058129, name, path, target);
}

/**
 * RemoveProfileCache drops a shared cache from a profile.
 */
export function RemoveProfileCache(profileSlug: string, cacheSlug: string): $CancellablePromise<void> {
    return $Call.ByID(629848113, profileSlug, cacheSlug);
}

/**
 * RemoveProfileMount drops a mount from a profile and detaches it.
 */
export function RemoveProfileMount(profileSlug: string, hostPath: string, targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(3855702870, profileSlug, hostPath, targetPath);
}

/**
 * RemoveProfileSkillItem drops a selection from a profile.
 */
export function RemoveProfileSkillItem(profileSlug: string, ref: $models.SkillRefRequest): $CancellablePromise<void> {
    return $Call.ByID(855797425, profileSlug, ref);
}

/**
 * RemoveRegistrySecret deletes registry pull credentials for one host.
 */
export function RemoveRegistrySecret(scope: string, host: string): $CancellablePromise<void> {
    return $Call.ByID(3013588355, scope, host);
}

/**
 * RemoveRule drops an allow/deny pattern from a profile.
 */
export function RemoveRule(slug: string, req: $models.RuleRequest): $CancellablePromise<void> {
    return $Call.ByID(4020660650, slug, req);
}

/**
 * RemoveSecret deletes a stored service secret.
 */
export function RemoveSecret(scope: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1612390584, scope, name);
}

/**
 * RemoveTemplate deletes a template image by tag or ID.
 */
export function RemoveTemplate(ref: string): $CancellablePromise<void> {
    return $Call.ByID(2203680990, ref);
}

/**
 * SandboxConfigDir returns the config directory of a sandbox.
 */
export function SandboxConfigDir(slug: string): $CancellablePromise<string> {
    return $Call.ByID(2731748656, slug);
}

/**
 * SandboxDetail returns the detail payload the sandbox page renders.
 */
export function SandboxDetail(name: string): $CancellablePromise<app$0.SandboxDetail> {
    return $Call.ByID(2726826130, name);
}

/**
 * SandboxPolicy returns the rules that apply to one sandbox.
 */
export function SandboxPolicy(name: string): $CancellablePromise<sbx$0.PolicyRule[] | null> {
    return $Call.ByID(3252575237, name);
}

/**
 * SandboxPolicyAction applies an allow/deny mutation scoped to one sandbox.
 */
export function SandboxPolicyAction(name: string, action: string, resources: string[] | null): $CancellablePromise<sbx$0.PolicyActionResult[] | null> {
    return $Call.ByID(3277562207, name, action, resources);
}

/**
 * SandboxTraffic returns the proxy log filtered to one sandbox.
 */
export function SandboxTraffic(name: string): $CancellablePromise<sbx$0.PolicyLog> {
    return $Call.ByID(1358447664, name);
}

/**
 * Search ranks the fleet sandboxes, profiles and caches together with the
 * skill, command and kit catalogs against a free-text query. Results are
 * best-first and capped server side.
 */
export function Search(query: string): $CancellablePromise<search$0.Result[] | null> {
    return $Call.ByID(1163934328, query);
}

/**
 * SetConfig writes the global configuration file.
 */
export function SetConfig(cfg: fleet$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(674095610, cfg);
}

/**
 * SetCustomSecret stores a placeholder secret bound to hosts.
 */
export function SetCustomSecret(req: $models.CustomSecretRequest): $CancellablePromise<void> {
    return $Call.ByID(473241439, req);
}

/**
 * SetRegistrySecret stores a registry credential.
 */
export function SetRegistrySecret(req: $models.RegistrySecretRequest): $CancellablePromise<void> {
    return $Call.ByID(1916033531, req);
}

/**
 * SetSandboxRunArgs stores the custom arguments appended after `--` to the
 * sandbox's connect run command; an empty value clears it.
 */
export function SetSandboxRunArgs(name: string, args: string): $CancellablePromise<void> {
    return $Call.ByID(2487115425, name, args);
}

/**
 * SetServiceSecret stores a service credential.
 */
export function SetServiceSecret(req: $models.ServiceSecretRequest): $CancellablePromise<void> {
    return $Call.ByID(851959799, req);
}

/**
 * StartDaemon starts the sandboxd daemon.
 */
export function StartDaemon(): $CancellablePromise<void> {
    return $Call.ByID(960737188);
}

/**
 * StartSandbox boots a stopped sandbox and converges its configuration.
 */
export function StartSandbox(name: string): $CancellablePromise<void> {
    return $Call.ByID(3564318391, name);
}

/**
 * StopSandbox halts a running sandbox.
 */
export function StopSandbox(name: string): $CancellablePromise<void> {
    return $Call.ByID(4269291435, name);
}

/**
 * Traffic returns the cross-sandbox proxy log.
 */
export function Traffic(): $CancellablePromise<sbx$0.PolicyLog> {
    return $Call.ByID(1314975677);
}

/**
 * UnassignProfile removes a profile from a sandbox.
 */
export function UnassignProfile(name: string, profileSlug: string): $CancellablePromise<void> {
    return $Call.ByID(2923123827, name, profileSlug);
}

/**
 * UpdateCache rewrites a shared cache definition.
 */
export function UpdateCache(slug: string, input: $models.CacheInput): $CancellablePromise<fleet$0.Cache> {
    return $Call.ByID(2257824741, slug, input);
}

/**
 * UpdateKitStore rewrites a kit repository registration.
 */
export function UpdateKitStore(slug: string, req: $models.KitStoreRequest): $CancellablePromise<app$0.KitStoreView> {
    return $Call.ByID(3203030384, slug, req);
}

/**
 * UpdateProfile rewrites a profile and returns its view.
 */
export function UpdateProfile(slug: string, req: $models.ProfileRequest): $CancellablePromise<app$0.ProfileView> {
    return $Call.ByID(1857103598, slug, req);
}

/**
 * UpdateSkillStore rewrites a skill store registration.
 */
export function UpdateSkillStore(slug: string, req: $models.SkillStoreRequest): $CancellablePromise<app$0.SkillStoreView> {
    return $Call.ByID(3957676007, slug, req);
}

/**
 * ValidateProfile runs `sbx kit validate` over a profile's config directory.
 */
export function ValidateProfile(slug: string): $CancellablePromise<app$0.KitValidation> {
    return $Call.ByID(3399392191, slug);
}

/**
 * ValidateSandbox runs `sbx kit validate` over a sandbox's config directory.
 */
export function ValidateSandbox(slug: string): $CancellablePromise<app$0.KitValidation> {
    return $Call.ByID(2458503613, slug);
}

/**
 * VersionInfo reports the running build version.
 */
export function VersionInfo(): $CancellablePromise<$models.VersionInfo> {
    return $Call.ByID(2246080484);
}
