// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Desktop from "./desktop.js";
export {
    Desktop
};

export type {
    CacheInput,
    CreateSandboxRequest,
    CustomSecretRequest,
    ExecRequest,
    Health,
    ImportSecretsRequest,
    MountRequest,
    PolicyActionRequest,
    ProfileRequest,
    ReapplyResult,
    RegistrySecretRequest,
    RuleRequest,
    ServiceSecretRequest,
    SkillStoreRequest,
    WorkspaceSpec
} from "./models.js";
