// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Notifier is the Wails service that owns the platform notification backend
 * and exposes a single Notify operation to the frontend. Wails starts it with
 * the application, which connects the platform notifier (D-Bus on Linux).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Notify sends one native desktop notification.
 */
export function Notify(title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(2747205003, title, body);
}
