// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig is the global sandwarden configuration file.
 */
export interface AppConfig {
    "terminals": TerminalPrefs;
    "notifications": boolean;
}

/**
 * Cache is one shared cache directory (sidecar only: a cache is a host bind
 * mount, which no kit can express).
 */
export interface Cache {
    "Slug": string;
    "Dir": string;
    "App": CacheApp;
}

/**
 * CacheApp is a shared cache definition.
 */
export interface CacheApp {
    "name": string;
    "description": string;
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
    "auto_attach": boolean | null;
    "enabled": boolean | null;
}

/**
 * EntityKind names the fleet object a loaded configuration file belongs to.
 */
export enum EntityKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Entity kinds used to key staleness by (kind, slug, file).
     */
    EntitySandbox = "sandbox",
    EntityProfile = "profile",
    EntityCache = "cache",
    EntitySkillStore = "skill-store",
    EntityKitStore = "kit-store",
    EntityConfig = "config",
};

/**
 * MountRef is a host bind mount: empty TargetPath keeps the host path.
 */
export interface MountRef {
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
}

/**
 * SkillRef points at one catalog item by store slug, kind and name.
 */
export interface SkillRef {
    "store": string;
    "kind": string;
    "name": string;
}

/**
 * StaleFile is one loaded file whose on-disk fingerprint changed.
 */
export interface StaleFile {
    "kind": EntityKind;
    "slug": string;
    "name": string;
    "file": string;
    "path": string;
}

/**
 * Staleness reports whether any loaded file changed on disk since the last
 * load, and which ones.
 */
export interface Staleness {
    "stale": boolean;
    "changed": StaleFile[] | null;
}

/**
 * TerminalPrefs is the global terminal-launcher preference.
 */
export interface TerminalPrefs {
    "enabled": string[] | null;
    "default": string;
}
