// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CustomSecret is a custom proxy-injected secret (`sbx secret set-custom`).
 */
export interface CustomSecret {
    "scope": string;
    "targets": string[] | null;
    "env": string;
    "placeholder": string;
    "masked": string;
    "kind"?: string;
    "source"?: string;
    "refresh"?: string;
}

/**
 * LogEntry is one allowed/blocked host record from the proxy.
 */
export interface LogEntry {
    "host": string;
    "vm_name": string;
    "proxy_type": string;
    "rule": string;
    "last_seen": string;
    "since": string;
    "count_since": number;
}

/**
 * MountInfo is a host path bind-mounted into a sandbox at runtime
 * (`sbx inspect --json` → runtime_mounts).
 */
export interface MountInfo {
    "host_path": string;
    "container_target"?: string;
    "read_only"?: boolean;
}

/**
 * PolicyActionResult is the daemon's per-action outcome. Error is set (and the
 * action failed) when the daemon rejected that action.
 */
export interface PolicyActionResult {
    "action": string;
    "resources"?: string[] | null;
    "sandbox_id"?: string;
    "error"?: string;
    "created"?: PolicyRuleRef[] | null;
    "existing"?: PolicyRuleRef[] | null;
    "removed"?: PolicyRuleRef[] | null;
}

/**
 * PolicyLog is the GET /policy/network/log response.
 */
export interface PolicyLog {
    "blocked_hosts": LogEntry[] | null;
    "allowed_hosts": LogEntry[] | null;
}

/**
 * PolicyRule is one rule from GET /policy/network/rules.
 */
export interface PolicyRule {
    "id": string;
    "name": string;
    "policy_id": string;
    "scope": string;
    "applies_to": string;
    "sandbox_id"?: string;
    "resource_type": string;
    "decision": string;
    "resources": string[] | null;
    "origin": string;
    "status": string;
    "editable": boolean;
}

/**
 * PolicyRuleRef identifies a rule created, matched or removed by a mutation.
 */
export interface PolicyRuleRef {
    "resource": string;
    "rule_id": string;
    "rule_name": string;
}

/**
 * PublishedPort is one host <-> sandbox port mapping.
 */
export interface PublishedPort {
    "host_ip": string;
    "host_port": number;
    "protocol": string;
    "sandbox_port": number;
}

/**
 * Secret is a stored service or registry secret (`sbx secret set`).
 */
export interface Secret {
    "scope": string;

    /**
     * "service" | "registry"
     */
    "type": string;

    /**
     * service name or registry host
     */
    "name": string;

    /**
     * what the CLI shows; never the real secret
     */
    "masked": string;
    "username"?: string;

    /**
     * resolver kind, e.g. "command" / "op" / "aws"
     */
    "kind"?: string;
    "source"?: string;
    "refresh"?: string;
}

/**
 * SecretList is the parsed `sbx secret ls --json` output.
 */
export interface SecretList {
    "stored": Secret[] | null;
    "custom": CustomSecret[] | null;
}

/**
 * WorkspaceMount is a host directory bind-mounted into a sandbox.
 */
export interface WorkspaceMount {
    "dir": string;
    "read_only"?: boolean | null;
}
