// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Kind identifies what an indexed document comes from: a fleet config entity
 * (sandbox, profile, cache) or a discovered catalog item (skill, command, kit).
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Indexed document kinds.
     */
    KindSkill = "skill",
    KindCommand = "command",
    KindKit = "kit",
    KindSandbox = "sandbox",
    KindProfile = "profile",
    KindCache = "cache",
};

/**
 * Result is one ranked hit.
 */
export interface Result {
    "kind": Kind;
    "store": string;
    "store_name": string;
    "name": string;
    "display_name"?: string;

    /**
     * Slug routes config entity hits; it is not part of the searchable text.
     */
    "slug"?: string;
    "description": string;
    "plugin"?: string;
    "kit_kind"?: string;

    /**
     * Agent is set on sandbox hits.
     */
    "agent"?: string;
    "score": number;
    "snippet"?: string;
}
