// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Kind identifies the catalog an indexed document comes from.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Indexed document kinds.
     */
    KindSkill = "skill",
    KindCommand = "command",
    KindKit = "kit",
};

/**
 * Result is one ranked hit.
 */
export interface Result {
    "kind": Kind;
    "id": number;
    "store_id": number;
    "store_name": string;
    "name": string;
    "display_name"?: string;
    "description": string;
    "plugin"?: string;
    "kit_kind"?: string;
    "score": number;
    "snippet"?: string;
}
