// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CustomSecret is a custom proxy-injected secret (`sbx secret set-custom`).
 */
export interface CustomSecret {
    "scope": string;
    "targets": string[] | null;
    "env": string;
    "placeholder": string;
    "masked": string;
    "kind"?: string;
    "source"?: string;
    "refresh"?: string;
}

/**
 * KitArgument is one caller-supplied input a kit declares.
 */
export interface KitArgument {
    "default"?: string | null;
    "required"?: boolean;
    "description"?: string;
    "enum"?: string[] | null;
    "pattern"?: string;
}

/**
 * KitCommand is one setup hook. Command is normalized to a single string
 * whether the spec declared it as a string or an argv array.
 */
export interface KitCommand {
    "command"?: string;
    "user"?: string;
    "description"?: string;
}

/**
 * KitCommandSet is the default and interactive argv of an agent kit.
 */
export interface KitCommandSet {
    "default"?: string[] | null;
    "interactive"?: string[] | null;
}

/**
 * KitEnvironment holds the static environment variables a kit sets.
 */
export interface KitEnvironment {
    "variables"?: { [_ in string]?: string } | null;
}

/**
 * KitFile is one static file a kit injects; its content is never surfaced.
 */
export interface KitFile {
    "path": string;
    "mode"?: string;
    "description"?: string;
}

/**
 * KitNetworkPolicy lists the allowed and denied egress hosts.
 */
export interface KitNetworkPolicy {
    "allow"?: string[] | null;
    "deny"?: string[] | null;
}

/**
 * KitPermissions is the egress policy a kit declares.
 */
export interface KitPermissions {
    "network"?: KitNetworkPolicy;
}

/**
 * KitPort is one container port a kit exposes.
 */
export interface KitPort {
    "container": number;
    "protocol"?: string;
    "name"?: string;
}

/**
 * KitRequires names the base agent a mixin composes onto.
 */
export interface KitRequires {
    "agent"?: string;
}

/**
 * KitSandbox is the sandbox image block of a kind=sandbox kit.
 */
export interface KitSandbox {
    "image"?: string;
    "entrypoint"?: string[] | null;
    "command"?: KitCommandSet;
}

/**
 * KitSetup is the install/startup hooks and injected files of a kit.
 */
export interface KitSetup {
    "install"?: KitCommand[] | null;
    "startup"?: KitCommand[] | null;
    "files"?: KitFile[] | null;
}

/**
 * KitSpec is the parsed `sbx kit inspect --json` payload the kit catalog and
 * detail views render. Fields the UI does not show are ignored.
 */
export interface KitSpec {
    "schemaVersion": string;
    "kind": string;
    "name": string;
    "version"?: string;
    "displayName"?: string;
    "description"?: string;
    "sourceURL"?: string;
    "requires"?: KitRequires;
    "sandbox"?: KitSandbox;
    "environment"?: KitEnvironment;
    "permissions"?: KitPermissions;
    "ports"?: KitPort[] | null;
    "setup"?: KitSetup;
    "arguments"?: { [_ in string]?: KitArgument } | null;
}

/**
 * LogEntry is one allowed/blocked host record from the proxy.
 */
export interface LogEntry {
    "host": string;
    "vm_name": string;
    "proxy_type": string;
    "rule": string;
    "last_seen": string;
    "since": string;
    "count_since": number;
}

/**
 * MountInfo is a host path bind-mounted into a sandbox at runtime
 * (`sbx inspect --json` → runtime_mounts).
 */
export interface MountInfo {
    "host_path": string;
    "container_target"?: string;
    "read_only"?: boolean;
}

/**
 * PolicyActionResult is the daemon's per-action outcome. Error is set (and the
 * action failed) when the daemon rejected that action.
 */
export interface PolicyActionResult {
    "action": string;
    "resources"?: string[] | null;
    "sandbox_id"?: string;
    "error"?: string;
    "created"?: PolicyRuleRef[] | null;
    "existing"?: PolicyRuleRef[] | null;
    "removed"?: PolicyRuleRef[] | null;
}

/**
 * PolicyLog is the GET /policy/network/log response.
 */
export interface PolicyLog {
    "blocked_hosts": LogEntry[] | null;
    "allowed_hosts": LogEntry[] | null;
}

/**
 * PolicyRule is one rule from GET /policy/network/rules.
 */
export interface PolicyRule {
    "id": string;
    "name": string;
    "policy_id": string;
    "scope": string;
    "applies_to": string;
    "sandbox_id"?: string;
    "resource_type": string;
    "decision": string;
    "resources": string[] | null;
    "origin": string;
    "status": string;
    "editable": boolean;
}

/**
 * PolicyRuleRef identifies a rule created, matched or removed by a mutation.
 */
export interface PolicyRuleRef {
    "resource": string;
    "rule_id": string;
    "rule_name": string;
}

/**
 * PublishedPort is one host <-> sandbox port mapping.
 */
export interface PublishedPort {
    "host_ip": string;
    "host_port": number;
    "protocol": string;
    "sandbox_port": number;
}

/**
 * Secret is a stored service or registry secret (`sbx secret set`).
 */
export interface Secret {
    "scope": string;

    /**
     * "service" | "registry"
     */
    "type": string;

    /**
     * service name or registry host
     */
    "name": string;

    /**
     * what the CLI shows; never the real secret
     */
    "masked": string;
    "username"?: string;

    /**
     * resolver kind, e.g. "command" / "op" / "aws"
     */
    "kind"?: string;
    "source"?: string;
    "refresh"?: string;
}

/**
 * SecretList is the parsed `sbx secret ls --json` output.
 */
export interface SecretList {
    "stored": Secret[] | null;
    "custom": CustomSecret[] | null;
}

/**
 * Template is one image in the sandbox runtime's template store
 * (`sbx template ls --json`).
 */
export interface Template {
    "id": string;
    "repository": string;
    "tag": string;
    "flavor": string;
    "created_at": string;
    "size": number;
}

/**
 * WorkspaceMount is a host directory bind-mounted into a sandbox.
 */
export interface WorkspaceMount {
    "dir": string;
    "read_only"?: boolean | null;
}
