// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fleet$0 from "../fleet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sbx$0 from "../sbx/models.js";

/**
 * AgentsDoc is the instructions file mounted read-only at
 * /home/agent/.agents/AGENTS.md in every running sandbox. Default reports
 * whether Content still matches the built-in template.
 */
export interface AgentsDoc {
    "path": string;
    "target": string;
    "content": string;
    "default": boolean;
}

/**
 * ApplyReport summarises one convergence pass over a sandbox's files.
 */
export interface ApplyReport {
    "rules_applied": number;
    "mounts_applied": number;
    "caches_applied": number;
    "skills_applied": number;
    "skills_removed": number;
    "warnings": string[] | null;
    "errors": string[] | null;
}

/**
 * ConfigFile is one configuration file of a sandbox or profile, as shown by
 * the read-only viewer. Error is set when the file is missing, too large or
 * invalid; Content still carries the raw text when it could be read.
 */
export interface ConfigFile {
    "name": string;
    "path": string;
    "content": string;
    "error"?: string;
}

/**
 * ConnectInfo carries the CLI commands that attach to a sandbox's agent.
 */
export interface ConnectInfo {
    "run": string;
    "shell": string;
}

/**
 * Event is the realtime envelope pushed over the websocket.
 */
export interface Event {
    "topic": Topic;
    "data"?: any;
    "ts": string;
}

/**
 * ImportReport is the result of one bulk import pass.
 */
export interface ImportReport {
    "results": ImportResult[] | null;
    "created": number;
    "configured": number;
    "failed": number;
}

/**
 * ImportResult is the outcome of importing one daemon sandbox into the config
 * directory.
 */
export interface ImportResult {
    "name": string;
    "status": string;
    "incomplete": boolean;
    "error"?: string;
}

/**
 * JobView is the queryable state of a job.
 */
export interface JobView {
    "id": string;
    "status": string;
    "output": string;
    "error"?: string;
}

/**
 * KitAddResult is the outcome of attaching a mixin kit to an existing
 * sandbox: the sbx CLI output plus the sidecar convergence pass that follows.
 */
export interface KitAddResult {
    "sandbox": string;
    "ref": string;
    "output"?: string;
    "report": ApplyReport;
}

/**
 * KitItemView is one catalog kit with the reference usable at create time and
 * its parsed spec for the detail view.
 */
export interface KitItemView {
    "store": string;
    "kind": string;
    "name": string;
    "display_name": string;
    "description": string;
    "version": string;
    "image": string;
    "requires_agent": string;
    "rel_path": string;
    "store_name": string;
    "ref": string;
    "spec": sbx$0.KitSpec;
}

/**
 * KitStoreView is a kit repository registration plus its checkout and sync
 * state.
 */
export interface KitStoreView {
    "slug": string;
    "name": string;
    "description": string;
    "url": string;
    "ref": string;
    "auth": string;
    "path": string;
    "synced_at": string;
    "error": string;
}

/**
 * KitValidation is the verdict of `sbx kit validate`.
 */
export interface KitValidation {
    "ok": boolean;
    "output": string;
}

/**
 * ProfileRef is a profile as referenced by one sandbox.
 */
export interface ProfileRef {
    "slug": string;
    "name": string;
    "default": boolean;
    "global": boolean;
}

/**
 * ProfileView is a profile file plus its derived links.
 */
export interface ProfileView {
    "slug": string;
    "name": string;
    "description": string;
    "default": boolean;
    "global": boolean;
    "allow": string[] | null;
    "deny": string[] | null;
    "mounts": fleet$0.MountRef[] | null;
    "caches": string[] | null;
    "skills": fleet$0.SkillRef[] | null;
    "sandboxes": string[] | null;
}

/**
 * SandboxCache is a configured cache plus its live attachment state for one
 * sandbox.
 * SandboxCache is a configured cache plus its live attachment state for one
 * sandbox.
 */
export interface SandboxCache {
    "slug": string;
    "name": string;
    "description": string;
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
    "auto_attach": boolean | null;
    "enabled": boolean | null;
    "attached": boolean;
    "direct": boolean;
    "profiles": string[] | null;
    "opted_out": boolean;
}

/**
 * SandboxDetail is the per-sandbox projection pushed on TopicSandbox.
 */
export interface SandboxDetail {
    "sandbox": SandboxSummary;
    "profiles": ProfileRef[] | null;
    "mounts": sbx$0.MountInfo[] | null;
    "mounts_error"?: string;

    /**
     * Incomplete reports a config directory adopted from the daemon without its original create parameters.
     */
    "incomplete": boolean;
    "image"?: string;
    "image_digest"?: string;
    "kits"?: string[] | null;
    "secrets": sbx$0.Secret[] | null;
    "custom_secrets": sbx$0.CustomSecret[] | null;
    "policy_rules": sbx$0.PolicyRule[] | null;
    "caches": SandboxCache[] | null;
    "profile_mounts": SandboxProfileMount[] | null;
    "direct_mounts": SandboxDirectMount[] | null;
    "additional_workspaces"?: sbx$0.WorkspaceMount[] | null;
    "skills": SandboxSkill[] | null;
}

/**
 * SandboxDirectMount is a sandbox-owned declared mount with its live state.
 */
export interface SandboxDirectMount {
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
    "attached": boolean;
}

/**
 * SandboxProfileMount is a profile mount as seen from one sandbox: the merged
 * target plus its opt-out and live attachment state.
 */
export interface SandboxProfileMount {
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
    "profile_names": string[] | null;
    "opted_out": boolean;
    "attached": boolean;
}

/**
 * SandboxSkill is a skill or command a sandbox exposes, with its mount
 * target, provenance and live mount state for the Skills tab.
 */
export interface SandboxSkill {
    "store": string;
    "kind": string;
    "name": string;
    "description": string;
    "plugin": string;
    "rel_path": string;
    "store_name": string;
    "target": string;
    "sources": string[] | null;
    "mounted": boolean;
    "conflict"?: string;
    "missing"?: boolean;
    "orphan"?: boolean;
}

/**
 * SandboxSummary is the list projection of a sandbox.
 */
export interface SandboxSummary {
    "name": string;
    "id": string;
    "agent"?: string;
    "status": string;
    "running": boolean;
    "workspace": string;
    "daemon_profile"?: string;
    "created_at"?: string | null;
    "stopped_at"?: string | null;
    "ports"?: sbx$0.PublishedPort[] | null;
    "mount_policy_denied": boolean;
    "profiles": string[] | null;
    "connect": ConnectInfo;

    /**
     * RunArgs is appended after `--` to the connect run command, if set.
     */
    "run_args": string;

    /**
     * CPUPercent is the sampled CPU usage, 0-100 across the sandbox CPUs.
     */
    "cpu_percent": number;

    /**
     * MemoryUsed/MemoryTotal are the sampled memory figures in bytes.
     */
    "memory_used_bytes": number;
    "memory_total_bytes": number;

    /**
     * Incomplete reports a config directory adopted from the daemon without its original create parameters.
     */
    "incomplete": boolean;
}

/**
 * SkillReconcileResult reports one convergence pass.
 */
export interface SkillReconcileResult {
    "applied": number;
    "removed": number;
    "errors": string[] | null;
}

/**
 * SkillStoreView is a skill store registration plus its checkout and sync
 * state.
 */
export interface SkillStoreView {
    "slug": string;
    "name": string;
    "description": string;
    "url": string;
    "ref": string;
    "auth": string;
    "path": string;
    "synced_at": string;
    "error": string;
}

/**
 * Topic identifies a realtime stream pushed to clients over the websocket.
 */
export enum Topic {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TopicSandboxes carries the sandbox summary list.
     */
    TopicSandboxes = "sandboxes",

    /**
     * TopicProfiles carries profile views with their rules and assignments.
     */
    TopicProfiles = "profiles",

    /**
     * TopicSecrets carries the stored secret inventory.
     */
    TopicSecrets = "secrets",

    /**
     * TopicTraffic carries the global proxy allow/deny log.
     */
    TopicTraffic = "traffic",

    /**
     * TopicPolicyRules carries every daemon policy rule.
     */
    TopicPolicyRules = "policy-rules",

    /**
     * TopicBlocked carries a single newly blocked host.
     */
    TopicBlocked = "blocked",

    /**
     * TopicCaches carries the shared cache configuration list.
     */
    TopicCaches = "caches",

    /**
     * TopicSkills carries the registered skill stores.
     */
    TopicSkills = "skills",

    /**
     * TopicKits is published when a kit repository or its catalog changes.
     */
    TopicKits = "kits",
};
