// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sbx$0 from "../sbx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * ConnectInfo carries the CLI commands that attach to a sandbox's agent.
 */
export interface ConnectInfo {
    "run": string;
    "shell": string;
}

/**
 * Event is the realtime envelope pushed over the websocket.
 */
export interface Event {
    "topic": Topic;
    "data"?: any;
    "ts": string;
}

/**
 * JobView is the queryable state of a job.
 */
export interface JobView {
    "id": string;
    "status": string;
    "output": string;
    "error"?: string;
}

/**
 * ProfileView is a profile with its rules and the sandboxes it is assigned to.
 */
export interface ProfileView {
    "id": number;
    "name": string;
    "description": string;
    "is_default": boolean;
    "is_global": boolean;
    "created_at": string;
    "updated_at": string;
    "rules": store$0.Rule[] | null;
    "items": store$0.SkillItem[] | null;
    "sandboxes": string[] | null;
}

/**
 * SandboxCache is a configured cache plus its live attachment state for one
 * sandbox.
 */
export interface SandboxCache {
    "id": number;
    "name": string;
    "description": string;
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
    "auto_attach": boolean;
    "enabled": boolean;
    "created_at": string;
    "updated_at": string;
    "attached": boolean;
}

/**
 * SandboxDetail is the per-sandbox projection pushed on TopicSandbox.
 */
export interface SandboxDetail {
    "sandbox": SandboxSummary;
    "profiles": store$0.Profile[] | null;
    "mounts": sbx$0.MountInfo[] | null;
    "secrets": sbx$0.Secret[] | null;
    "custom_secrets": sbx$0.CustomSecret[] | null;
    "policy_rules": sbx$0.PolicyRule[] | null;
    "caches": SandboxCache[] | null;
    "additional_workspaces"?: sbx$0.WorkspaceMount[] | null;
    "skills": SandboxSkill[] | null;
}

/**
 * SandboxSkill is a skill or command a sandbox exposes, with its mount target,
 * provenance and live mount state for the Skills tab.
 */
export interface SandboxSkill {
    "id": number;
    "store_id": number;
    "store_name": string;
    "kind": string;
    "name": string;
    "description": string;
    "plugin": string;
    "rel_path": string;
    "target": string;
    "sources": string[] | null;
    "mounted": boolean;
    "conflict"?: string;
    "missing"?: boolean;
    "orphan"?: boolean;
}

/**
 * SandboxSummary is the list projection of a sandbox.
 */
export interface SandboxSummary {
    "name": string;
    "id": string;
    "agent"?: string;
    "status": string;
    "running": boolean;
    "workspace": string;
    "daemon_profile"?: string;
    "created_at"?: string | null;
    "stopped_at"?: string | null;
    "ports"?: sbx$0.PublishedPort[] | null;
    "mount_policy_denied": boolean;
    "profiles": string[] | null;
    "connect": ConnectInfo;
}

/**
 * SkillReconcileResult reports what one reconcile pass changed.
 */
export interface SkillReconcileResult {
    "applied": number;
    "removed": number;
    "errors": string[] | null;
}

/**
 * Topic identifies a realtime stream pushed to clients over the websocket.
 */
export enum Topic {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TopicSandboxes carries the sandbox summary list.
     */
    TopicSandboxes = "sandboxes",

    /**
     * TopicProfiles carries profile views with their rules and assignments.
     */
    TopicProfiles = "profiles",

    /**
     * TopicSecrets carries the stored secret inventory.
     */
    TopicSecrets = "secrets",

    /**
     * TopicTraffic carries the global proxy allow/deny log.
     */
    TopicTraffic = "traffic",

    /**
     * TopicPolicyRules carries every daemon policy rule.
     */
    TopicPolicyRules = "policy-rules",

    /**
     * TopicBlocked carries a single newly blocked host.
     */
    TopicBlocked = "blocked",

    /**
     * TopicCaches carries the shared cache configuration list.
     */
    TopicCaches = "caches",

    /**
     * TopicSkills carries the registered skill stores.
     */
    TopicSkills = "skills",
};
