// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheInput is the shared-cache create/update payload.
 */
export interface CacheInput {
    "name": string;
    "description": string;
    "host_path": string;
    "target_path": string;
    "read_only": boolean;
    "auto_attach": boolean;
    "enabled": boolean;
}

/**
 * CreateSandboxRequest mirrors the create form payload.
 */
export interface CreateSandboxRequest {
    "agent": string;
    "workspaces": WorkspaceSpec[] | null;
    "name": string;
    "cpus": number;
    "memory": string;
    "profile": string;
    "template": string;
    "publish": string[] | null;
    "env": string[] | null;
    "deny_network": string[] | null;
    "clone": boolean;
    "attach_caches": boolean;
    "job_id": string;
}

/**
 * CustomSecretRequest is the custom (placeholder) secret payload.
 */
export interface CustomSecretRequest {
    "hosts": string[] | null;
    "env": string;
    "value": string;
    "ref": string;
    "command": string;
    "placeholder": string;
    "refresh": string;
    "scope": string;
    "overwrite": boolean;
}

/**
 * ExecRequest is the one-shot command payload.
 */
export interface ExecRequest {
    "command": string;
    "job_id": string;
}

/**
 * Health reports the daemon socket and CLI in use.
 */
export interface Health {
    "ok": boolean;
    "socket": string;
    "sbx_binary": string;
}

/**
 * ImportSecretsRequest is the bulk import payload.
 */
export interface ImportSecretsRequest {
    "service": string;
    "all": boolean;
    "dry_run": boolean;
    "force": boolean;
    "job_id": string;
}

/**
 * MountRequest is the add-mount payload.
 */
export interface MountRequest {
    "path": string;
    "target": string;
    "read_only": boolean;
}

/**
 * PolicyActionRequest is the policy action payload.
 */
export interface PolicyActionRequest {
    "action": string;
    "resources": string[] | null;
    "sandbox_id": string;
    "id": string;
}

/**
 * ProfileRequest is the profile create/update payload.
 */
export interface ProfileRequest {
    "name": string;
    "description": string;
    "is_default": boolean;
    "is_global": boolean;
}

/**
 * ReapplyResult reports the outcome of re-applying a sandbox's caches.
 */
export interface ReapplyResult {
    "applied": number;
    "errors": string[] | null;
}

/**
 * RegistrySecretRequest is the registry secret payload.
 */
export interface RegistrySecretRequest {
    "host": string;
    "username": string;
    "password": string;
    "scope": string;
    "overwrite": boolean;
}

/**
 * RuleRequest is the profile rule payload.
 */
export interface RuleRequest {
    "decision": string;
    "pattern": string;
}

/**
 * ServiceSecretRequest is the service secret payload.
 */
export interface ServiceSecretRequest {
    "service": string;
    "scope": string;
    "value": string;
    "ref": string;
    "command": string;
    "refresh": string;
    "overwrite": boolean;
}

/**
 * SkillStoreRequest mirrors the skill store form payload.
 */
export interface SkillStoreRequest {
    "name": string;
    "description": string;
    "url": string;
    "ref": string;
}

/**
 * WorkspaceSpec is one workspace entry of the create form.
 */
export interface WorkspaceSpec {
    "path": string;
    "read_only": boolean;
}
